import { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  return knex.raw(`
    CREATE TABLE categories (
      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name text NOT NULL
    );
    CREATE TABLE categories_posts (
      category_id int REFERENCES categories(id),
      post_id int REFERENCES posts(id),
      PRIMARY KEY (category_id, post_id)
    );
  `);
}

export async function down(knex: Knex): Promise<void> {
  return knex.raw(`
    DROP TABLE categories, categories_posts;
  `);
}
